### ISSUE TITLE
[BUG] - ES modules import "./some-lib.css" seems not to end up in the shadow-root

### ISSUE THREAD

**Issue by carlos22** [baiwusanyu-c/unplugin-vue-ce#118]
### Describe the bug

When using a library inside as child of your CE component that uses the ES modules `import "./mylib.css"` (in the `<script>` tag!) the css does not end up in the shadow dom but in the regular dom.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nqrj24 (should work now)

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/unplugin/unplugin-vue-ce/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a unplugin-vue-ce issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/unplugin/unplugin-vue-ce/assets/32354856/bdf72410-d88e-49e2-ae22-331294315405)
![image](https://github.com/unplugin/unplugin-vue-ce/assets/32354856/d5fbcb73-fb22-43c7-812c-b197443b4265)
![image](https://github.com/unplugin/unplugin-vue-ce/assets/32354856/f03a8524-245c-4ec1-8109-2be00582ab89)
I need more information to reproduce the problem

**Comment by baiwusanyu-c** [comment]
Are you referring to a third-party component library (such as vuetify)?

**Comment by carlos22** [comment]
> Are you referring to a third-party component library (such as vuetify)?

For example. Anything that is imported with a `import "style.css"` in the head. This style will not end up in the shadow dom even if the import was done in a sub component. The example I provided seems to be the original one, sorry for that I had it working but might have lost the link somehow...

**Comment by carlos22** [comment]
![grafik](https://github.com/unplugin/unplugin-vue-ce/assets/526996/e61ad518-6350-41c0-9848-192830e4d363)
![grafik](https://github.com/unplugin/unplugin-vue-ce/assets/526996/389f16c9-9b4b-4b8d-a2e0-770b578eacc9)

**Comment by carlos22** [comment]
This should work now: https://stackblitz.com/edit/vitejs-vite-nqrj24

**Comment by carlos22** [comment]
Cool, thanks for the fast fix :)
