### ISSUE TITLE
Vue Router + Pinia support?

### ISSUE THREAD

**Issue by mrcego** [baiwusanyu-c/unplugin-vue-ce#2]
Hey @baiwusanyu-c!

We were recently working in getting support for plugins like Vue Router and Pinia using [a wrapper](https://github.com/EranGrin/vue-web-component-wrapper). It works nicely, but we would like to improve style handling using your vite plugin. Do you mind if put us in the right direction to do that? We are testing now and it collides with wrapper workaround.

Thanks in advance!

**Comment by baiwusanyu-c** [comment]
Can you provide me with a small demo that fits your usage scenario? I need to think about how to make this compatible

**Comment by baiwusanyu-c** [comment]
I noticed that the plugin reported an error in webpack, it was a problem with unplugin, I fixed it

**Comment by mrcego** [comment]
> Can you provide me with a small demo that fits your usage scenario? I need to think about how to make this compatible

Could you check this, please? https://github.com/EranGrin/vue-web-component-wrapper/pull/3

`demo-app-vite` could be used when you want to embed a microfrontend in a, for example, Codeigniter (PHP) view with Pinia, Vue Router, Veevalidate and others dependencies that dont work via CE normally. 

This workaround allows us to build an Custom Elements where produced JS file could be imported and get props from Codeigniter view. The issue here is the styles from Tailwind, scoped styles from components and styles from another sources like imported styles from assets. The util what try to fix the issue can be found inside `package` folder, `web-component-util.ts`.

Thanks in advance.

**Comment by mrcego** [comment]
@baiwusanyu-c I noticed you created a workaround for above scenario. Thanks a lot for your work! It's outstanding. 

I was trying latest beta, but look like Tailwind is ignored. I tested several ways for include into style parsing without success. Do you mind if you check this repro? https://stackblitz.com/edit/vitejs-vite-xxzqjw

Thanks in advance.

**Comment by baiwusanyu-c** [comment]
Support for css frameworks has not yet been implemented, and I have been busy with some other things recently. In a few days, I will think about how to implement them

**Comment by baiwusanyu-c** [comment]
Due to the style isolation caused by the existence of shadow, if you want to support tailwind, you have to consider adding the style of tailwind to each shadow. As a temporary solution, you can manually add it to the root component of each shadow.
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
e.g
```
// Entry.vue
<template>
  <header class="bg-blue-300 rounded-lg shadow-lg p-4 mx-0 md:mx-20">
    <nav>
      <ul class="flex justify-between sm:mx-1 md:mx-20">
        <li>
          <router-link to="/">Home</router-link>
        </li>
        <li>
          <router-link to="/test1">Test route 1</router-link>
        </li>
        <li>
          <router-link to="/test2">Test route 2</router-link>
        </li>
        <li>
          <router-link to="/test3">Test route 3</router-link>
        </li>
      </ul>
    </nav>
  </header>
  <main class="mt-4 p-4 mx-0 md:mx-20 bg-gray-200 rounded-lg shadow-lg">
    <router-view />
  </main>
</template>

<script lang="ts">
export default {
  name: 'Main',
  props: {
    apiToken: { type: String, required: true },
    baseUri: { type: String, default: 'test.me' },
  },

  data: () => ({
    configuration: {},
    credentials: {
      apiToken: '',
      baseUri: '',
    },
  }),

  created() {
    console.log(this);
  },
};
</script>
<style>
@tailwind base;
@tailwind components;
@tailwind utilities;
.test-heading {
  font-size: 2em;
  margin-top: 2rem;
}
a {
  @apply text-gray-900 hover:text-gray-700;
}
</style>

```

**Comment by mrcego** [comment]
Hi @baiwusanyu-c 

Yeah, I see this workaround in [this issue from nuxt-custom-elements](https://github.com/GrabarzUndPartner/nuxt-custom-elements/issues/433#issuecomment-1557680161). The weird thing here is, I tested it some days ago but putting tailwind imports into a css file and It didn't work.
