### ISSUE TITLE
When importing the same component twice, the styles only apply to the first one. 

### ISSUE THREAD

**Issue by SavkaTaras** [baiwusanyu-c/unplugin-vue-ce#49]
Hello,
I hope you are doing well.

I am facing the issue when I include the component twice on the page (index.html). The second copy of the same component doesn't have nested styles. 

UPDATE: We build web components using vue lib dev mode. Then we import these components as my-lib.umd.js on index.html vie script tag.

I use Vite 4.2.0 and vue 3.3.4 to build out web components.

Version:
"@unplugin-vue-ce/sub-style": "^1.0.0-beta.9",

Thank you.

**Comment by baiwusanyu-c** [comment]
Hi, can you provide a repository that reproduces the problem? 😀

**Comment by SavkaTaras** [comment]
Hello,

It's a company resource and I can't, but I will try to create a boogey repo with issue reproduction tomorrow. I will post a url tonight/tomorrow.

Thank you,
Taras

**Comment by baiwusanyu-c** [comment]
This problem seems to be easily reproducible in non-lib mode, but I am not sure, I created a PR for this, and I can only confirm whether this PR is really correct after you provide the repo

**Comment by SavkaTaras** [comment]
Hello @baiwusanyu-c 

Please see repo:

https://github.com/SavkaTaras/vue-cue-issues

Run 
npm run build 

and then 

npm run dev 

This should provide a result

**Comment by SavkaTaras** [comment]
Hello @baiwusanyu-c ,

Please let me know if I can help in some way to get this issue resolved. The plugin you created is great for development, it's just this issue is kind of preventing us from using it.

I and a community really appreciate your hard work.

Thank you,
Taras

**Comment by baiwusanyu-c** [comment]
<img width="337" alt="image" src="https://github.com/baiwusanyu-c/unplugin-vue-ce/assets/32354856/f6e8b600-d4af-4ea4-bc36-1315798bafe6">

**Comment by SavkaTaras** [comment]
Thank you so much! That's awesome! I will do some tests later today.

**Comment by SavkaTaras** [comment]
@baiwusanyu-c it seems to have an issue when we use `defineAsyncComponent` the following:

	const ComponentB = defineAsyncComponent(() =>
		import("../ComponentB/ComponentB.vue")
	);

At this point it does not inject the style. Would it be possible to look into this as well?

Here's what creates an issue:

https://github.com/SavkaTaras/vue-cue-issues/blob/master/src/components/ComponentA/ComponentA.vue

Thank you,
Taras

**Comment by SavkaTaras** [comment]
I moved this request to the following link:

https://github.com/baiwusanyu-c/unplugin-vue-ce/issues/61

Thank you
