### ISSUE TITLE
ERROR: [plugin: externalize-deps] Failed to resolve entry for package "unplugin-vue-ce".

### ISSUE THREAD

**Issue by mrcego** [baiwusanyu-c/unplugin-vue-ce#70]
Hi @baiwusanyu-c!

Thanks again for supporting CE and Vue 3 community, and keep nailing it!

Latest beta look like has an issue with package.json config for import/export. I tested beta.13 and this issue doesn't occurs.

![Captura de pantalla 2023-08-24 a la(s) 1 53 28 p m](https://github.com/baiwusanyu-c/unplugin-vue-ce/assets/65884507/d051a015-5b2f-4495-a9e8-aeb1347b0fa4)

**Comment by baiwusanyu-c** [comment]
When I added the webpack test project to the project, I don’t know why the ts build error occurred, which caused the ci to fail to run normally. I manually released beta14 on my pc, but it seemed that the wrong path caused the release Package is missing some content. I'm sorry

**Comment by baiwusanyu-c** [comment]
Try beta15 to see if this problem still exists

**Comment by mrcego** [comment]
Thanks @baiwusanyu-c. Working again as expected. 

Proceed to close issue as completed.
