### ISSUE TITLE
createCEApp instance like createApp, is it possible?

### ISSUE THREAD

**Issue by mrcego** [baiwusanyu-c/unplugin-vue-ce#8]
Hi! Me again, but n-times 🥲.

There is an use case here when try to use dependencies that relay [in a completed `createApp` instance](https://v3-migration.vuejs.org/breaking-changes/global-api.html#a-new-global-api-createapp), like [mitt](https://github.com/developit/mitt). this is an example using [vue-web-component-wrapper](https://github.com/EranGrin/vue-web-component-wrapper/blob/2c3daabf4835cf286c6903eec1921c1d8b7e9f33/package/src/web-component-util.js#L74) using [`app.provides`](https://vuejs.org/guide/components/provide-inject.html#app-level-provide) to passthrough emitter to any child component. 

```javascript
export const defineCustomElementWrapped = (component, { plugins = [] } = {}) =>
  defineCustomElement({
    styles: component.styles.map((style) => {
      return style.replace(':root', ':host').replace('body {', '#app {')
    }),
    props: component.props,
    setup(props) {
      const app = createApp({})

      // install plugins
      plugins.forEach(app.use)

      app.provide('emitter', emitter) // <-- HERE!!

      const inst = getCurrentInstance() as ComponentInternalInstance & AppContext
      Object.assign(inst!.appContext, app._context)
      Object.assign(inst!.provides, app._context.provides)

      return () =>
        h(component, {
          ...props,
        })
    },
  })
```

when I want to use `createCEApp` API, it just expose `mount` and `use` functions. I was trying to merge both `_context` and `_context.provides` properties without success.

![Captura de pantalla 2023-06-07 a la(s) 11 01 04 a m](https://github.com/baiwusanyu-c/unplugin-vue-ce/assets/65884507/0c7b1f8e-0cfc-4820-853f-4b1ecf8b6daf)

Thanks in advance for your help.

**Comment by baiwusanyu-c** [comment]
Thanks for your feedback
